### ISSUE TITLE
List of target questions

### ISSUE THREAD

**Issue by tlevine** [CivOmega/civomega#11]
In order to choose which databases to import, it might help to have a list of questions that we'd want to ask of dataomega. Do y'all have any in mind? Maybe things that journalists often need to look up?

**Comment by mtigas** [comment]
There’s a list for Census-specific data, donated by [CensusReporter](http://censusreporter.org/) — https://github.com/CivOmega/civomega/blob/master/census/sample_questions.txt — but at the moment it’s open to what people 1) want to answer and implement and 2) what data they have on hand that can be answered.

**Comment by chriszs** [comment]
I'm interested in what people have been asking of it so far. I know I asked half a dozen questions before realizing it was limited to the question types in the examples.

**Comment by slifty** [comment]
Agreed; we should be storing what people are asking so we know what to target next.  This is probably worth doing before the potential question-mapping toolkit development.  We'll start with something simple and then maybe we'll notice trends in what folks are asking.

**Comment by slifty** [comment]
The new version really drives people into asking questions that the system can answer.  I'm going to close this task since it's old, but since right now we aren't allowing people to ask questions that don't match a pattern.
