### ISSUE TITLE
Accented characters in query

### ISSUE THREAD

**Issue by cynddl** [CivOmega/civomega#14]
Characters like ç, û, ü, ñ are raising an error. A question like _When has François visited the White House?_ return _We don't understand this kind of question yet, but that should change eventually._ but with a "c" instead of a "ç", the result is ok.

**Comment by miguelpaz** [comment]
Same thing in spanish language. Anyway to support UTF-8?

**Comment by chriszs** [comment]
Thanks for pointing this out. Pull request pending. Though I'm not sure the White House log API even has Unicode names in it. _When has François visited the White House?_ will just tell you it couldn't find anyone with that name.
